spec:
  template:
    spec:
      containers:
      - name: gitlab
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          value: >
            external_url 'https://gitlab.local';
            nginx['listen_port'] = 80;
            nginx['listen_https'] = false;
            letsencrypt['enable'] = false;
            gitlab_rails['lfs_enabled'] = true;
            gitlab_rails['gitlab_shell_ssh_port'] = 22;
            gitlab_rails['time_zone'] = 'Brazil/East';
            registry['enable'] = true;
            registry_external_url 'https://registry.gitlab.local';
            registry_nginx['listen_port'] = 5005;
            registry_nginx['listen_https'] = false;
            gitlab_rails['registry_path'] = '/var/opt/registry/storage';
            registry_nginx['proxy_set_headers'] = {
              "X-Forwarded-Proto" => "https",
              "X-Forwarded-Ssl" => "on",
              "Host" => "registry.gitlab.local"
            };
        ports:
        - containerPort: 5005
          name: 5005-registry
        volumeMounts:
        - mountPath: /var/opt/registry/storage
          name: gitlab-registry-storage
      volumes:
        - name: gitlab-registry-storage
          persistentVolumeClaim:
            claimName: gitlab-claim3