apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-claim3
  namespace: gitlab
  labels:
    app: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi