apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    app: gitlab
spec:
  selector:
    app: gitlab
  ports:
  - name: 80-http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: 22-ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: 5005-registry
    port: 5005
    protocol: TCP
    targetPort: 5005
  externalTrafficPolicy: Local
  type: LoadBalancer
